### ISSUE TITLE
DocReq: Cannot establish new user with accumelated values

### ISSUE THREAD

**Issue by adrianfk** [arnaugarcia/sallefy#142]
Documentation request:

The API contains alot of calls that seem related to establishing a user.

However, it it seems like I can not configure the input objects correctly, or I am missing the point.
As of now I have only been able to get the response of 403 "Not authorized".

Additionally, I have not been able to see how the client is supposed to insert/assosiate the inputed password with the created user, as there are none of the previously mentioned API calls that actually include this property as an entry.

An further elaboration to how this is planned to be pieced together would be greatly appreciated.

**Comment by arnaugarcia** [comment]
Hi!
To register an user you should make a POST request to this endpoint: 
`/api/register`
with a user as a request payload:
```
{
  "email": "string",
  "firstName": "string",
  "lastName": "string",
  "login": "string",
  "password": "string"
}
```
Its true that the API documentation does not provide the password field on it so it may create consfusion... (I'll update this in the next release :P )

And in order to obtain the token you must make a POST request with the user and password on the body consuming this endpoint:
`/api/authenticate`
`{"username":"test","password":"test"}`

Hope that it helps :D

**Comment by adrianfk** [comment]
Thank you! That was very helpful, now it works. :D

**Comment by arnaugarcia** [comment]
Glad to help ;D
