### ISSUE TITLE
show tracks (/api/tracks) Get request 

### ISSUE THREAD

**Issue by amirazzam2000** [arnaugarcia/sallefy#152]
when filtered by most played it returns only 4 songs

`curl -X GET "http://sallefy.eu-west-3.elasticbeanstalk.com/api/tracks?played=true" -H "accept: */*" -H "Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkdWRlIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTU4NzA0NjU0M30.jAqmR2l7s3CZaxchkVXzx3KlLFRYdlL_8FAch11q4ohV9uNo_zZcRay330OSDsIoxkpT3be3GBcpu7ZP3vwKDw"`

**Comment by arnaugarcia** [comment]
Hey! This is because a songs needs to be played. To play a song you should make a PUT request to this endpoint `http://sallefy.eu-west-3.elasticbeanstalk.com/api/tracks/{id}/play` with the latitude and longitude inside the body. I've teste it with the Track number 21 (Julia Michaels - Issues). As you can see now in the request it returns the song.

**Comment by amirazzam2000** [comment]
Oh okay that makes sense, Thank you very much  From: Arnau GarciaSent: Monday, March 30, 2020 5:35 PMTo: arnaugarcia/sallefyCc: amirazzam2000; AuthorSubject: Re: [arnaugarcia/sallefy] show tracks (/api/tracks) Get request (#152) Hey! This is because a songs needs to be played. To play a song you should make a PUT request to this endpoint http://sallefy.eu-west-3.elasticbeanstalk.com/api/tracks/{id}/play with the latitude and longitude inside the body. I've teste it with the Track number 21 (Julia Michaels - Issues). As you can see now in the request it returns the song.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
